#!/bin/bash
alias cl='clear; ls'
alias TODO='todo.py rft'

alias ll='ls -la'
ls() { 
  if [[ $1 == "-la" ]]; 
  then command ls $@ | more; else command ls "$@"; fi; 
}
alias cd..='cd ..'
alias vi='vim'
alias svi='sudo vi'
alias vis='vim "+set si"'
alias apt-get="sudo apt-get"
alias grep='grep --color=auto'
alias mkdir='mkdir -p'

# Notes
alias todo='more ~/Dropbox/notes/TODO'
alias vt='vim ~/Dropbox/notes/TODO'
alias food='more ~/Dropbox/notes/food'
alias vf='vim ~/Dropbox/notes/food'
